CREATE DATABASE burgers_db;

USE burgers_db;

CREATE TABLE burgers (
	id INT AUTO_INCREMENT NOT NULL,
	burger_name VARCHAR(200) NOT NULL,
	devoured BOOLEAN DEFAULT false,
	customerId INTEGER
	createdAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
	updatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	PRIMARY KEY(id)
);

CREATE TABLE customers (
	id INT AUTO_INCREMENT NOT NULL,
	customer_name VARCHAR(75) NOT NULL
	PRIMARY KEY(id)
)